### ISSUE TITLE
[FEAT] Oauth 관련 설정

### ISSUE THREAD

**Issue by tnwls000** [Gongkademy/Gongkademy_Service_Back#23]
## 어떤 기능인가요?
> Oauth와 관련된 설정을 추가합니다.

## 작업상세내용
- [ ] application.properties에 oauth 관련 설정 추가
- [ ] application-local.properties에 oauth 관련 설정 추가

## 참고할만한 자료 (선택)
- 레퍼런스가 있다면 남겨주세요.

**Comment by sevin98** [comment]
Oauth
