### ISSUE TITLE
[REFACTOR] Entity 리팩토링

### ISSUE THREAD

**Issue by jinchandol** [Gongkademy/Gongkademy_Service_Back#51]
## 어떤 기능인가요?
> Board Entity 수정

## 작업상세내용
- [x] Entity 리팩토링

## 참고할만한 자료 (선택)
- 레퍼런스가 있다면 남겨주세요.

**Comment by yknlwca** [comment]
새로운 방법으로 해보는 거 너무너무 좋아요
